= Usage instructions

Install python3-zmq on both client and server

[source,bash]
----
sudo apt install python3-zmq
----

== LED server

Install neopixel library for the RPi

[source,bash]
----
sudo pip3 install rpi_ws281x adafruit-circuitpython-neopixel
sudo python3 -m pip install --force-reinstall adafruit blinka
----

Run the neopixel server with sudo privileges (for use of the neopixel library sudo is needed, see: link:https://learn.adafruit.com/neopixels-on-raspberry-pi/python-usage[more explanation here]) from this directory with:

[source,bash]
----
sudo ./led_server.py
----

To have the LED server start at boot, copy the `led-server.service` file to the `/etc/systemd/system/` directory. Make sure you point to the correct path on the `ExecStart=...` line.
the script will be started with root privileges so the neopixels will work.

[source,bash]
----
# copy the .service file to the systemd directory
sudo cp led-server.service /etc/systemd/system/
# set correct permissions
sudo chmod +x /etc/systemd/system/led-server.service
# the --now argument will enable _and_ start the service
systemctl enable --now led-server.service
----

== LED client

run the led client from the command line by specifying the host to connect to, and the command to give the LED server. You can set the color or brightness.

The server will respond with a "success" or "fail" reply

[source,bash]
----
python led_client.py -n raspberrypi -c color_o
----

== CAMERA server

The camera server takes a picture at a clients request. It saves the image locally, opens as numpy image (with PIL) and sends the data to the client.

[source,bash]
----
./camera_server.py
----

== CAMERA client

The client sends a request "pic" to the server and receives a numpy array. The numpy array is saved locally (with PIL).

[source,bash]
----
python camera_client.py -n raspberrypi -c pic
----